sonar.host.url=https://sonarcloud.io
sonar.organization=velatura-services
sonar.projectName=palo-alto-failover
sonar.projectKey=velatura_palo-alto-failover
sonar.projectVersion=1.1.0
sonar.sources=lambda_functions/palo_alto_health_check/src,\
lambda_functions/palo_alto_failover/src,\
lambda_functions/palo_alto_sync_config/src,\
lambda_functions/palo_alto_utils/src
sonar.language=py
sonar.python.version=3.13
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=false
sonar.python.coverage.reportPaths=coverage.xml
